### ISSUE TITLE
error of dividing zeros

### ISSUE THREAD

**Issue by yudl21132** [cabooster/DeepCAD#10]
I got an error when I tried to train a model myself, and I think this "s_num" variable is not defined by myself. Could I possibly try to change it to a different value somewhere in the code for fixing this issue? Thanks!  

"stack_num ----->  172
whole_w ----->  512
whole_h ----->  512
whole_s ----->  500
w_num ----->  5
h_num ----->  5
s_num ----->  1
Traceback (most recent call last):
  File "train.py", line 66, in <module>
    name_list, noise_img, coordinate_list = train_preprocess_lessMemoryMulStacks(opt)
  File "/home/Documents/DeepCAD/DeepCAD_pytorch/data_process.py", line 266, in train_preprocess_lessMemoryMulStacks
    gap_s2 = get_gap_s(args, noise_im, stack_num)
  File "/home/Documents/DeepCAD/DeepCAD_pytorch/data_process.py", line 186, in get_gap_s
    gap_s = math.floor((whole_s-args.img_s*2)/(s_num-1))
ZeroDivisionError: division by zero
"

**Comment by yudl21132** [comment]
Never mind. I think I figured it out.
